# Generated by Django 5.2.4 on 2025-07-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='Url',
            field=models.CharField(default='', max_length=60, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='Name',
            field=models.CharField(max_length=60, verbose_name='Название'),
        ),
    ]
